--- # misdsd_primarydb.yml

database_global_database: STGDSD
database_taf_service: STGDSD_TAF
database_primary_unique: STGDSD
database_primary_sid: STGDSD
database_parameters:
   sga_max_size: 1G
   sga_target: 1G
