--- # misdsd_primarydb.yml

database_global_database: STGDSD
database_taf_service: STGDSD_TAF
database_primary_unique: STGDSD
database_primary_sid: STGDSD
database_parameters:
   sga_max_size: 1G
   sga_target: 1G
rman_retention_policy: RECOVERY WINDOW OF 31 DAYS
sqlnet_parameters:
   grid:
         SQLNET.INBOUND_CONNECT_TIMEOUT: 300
   database:
         SQLNET.INBOUND_CONNECT_TIMEOUT: 300
listener_parameters:
   grid:
       INBOUND_CONNECT_TIMEOUT_LISTENER: 300
delius_users:
  bbuchan_dba:
  rsingh_dba:
  dreid_dba:
  sgandalwar_dba:
  kmoss_dba:
oracle_software:
  version: 19.16
  superset_patch: p34130714_190000_Linux-x86-64.zip
  ojvm_patch: p34086870_190000_Linux-x86-64.zip
  opatch:
    version: 12.2.0.1.32
    filename: p6880880_190000_Linux-x86-64.12.2.0.1.32.zip