--- # misdsd_primarydb.yml

database_global_database: STGDSD
database_taf_service: STGDSD_TAF
database_primary_unique: STGDSD
database_primary_sid: STGDSD
database_parameters:
   sga_max_size: 1G
   sga_target: 1G
rman_retention_policy: RECOVERY WINDOW OF 31 DAYS
sqlnet_parameters:
   grid:
         SQLNET.INBOUND_CONNECTION_TIMEOUT: 300
   database:
         SQLNET.INBOUND_CONNECTION_TIMEOUT: 300
delius_users:
  bbuchan_dba:
  rsingh_dba:
  dreid_dba:
  sgandalwar_dba:
  kmoss_dba: