--- # delius_primarydb.yml

database_global_database: TRNDA
database_taf_service: TRNDA_TAF
database_primary_unique: TRNDA
database_primary_sid: TRNDA
delius_users:
  bbuchan_dba:
  kmoss_dba:
  dbelton_dba:
oracle_software:
      version: '19.25'
      combo_patch: p36866740_190000_Linux-x86-64.zip
      opatch:
          version: 12.2.0.1.43
          filename: p6880880_190000_Linux-x86-64.12.2.0.1.43.zip
database_parameters:
   sga_max_size: 2G
   sga_target: 2G
# OFFENDER_DELTA and DOMAIN_EVENT are dynamic tables cleared down by Integration Services.
# Prevent changing these to unrepresentative statistics.
database_locked_statistics:
   - schema_name: DELIUS_APP_SCHEMA
     table_names:
      - DOC_MIGRATION_QUEUE_TAB: ALL
      - OFFENDER_DELTA: ALL
      - DOMAIN_EVENT: ALL
required_patches:
    p35012866:
      patch_files:
         - target_version: "19.18"
           filename: p35012866_1918000DBRU_Linux-x86-64.zip
      description: "BUG_33527739_APPLY.SQL GOT ORA-13516: AWR OPERATION FAILED: CATPROC NOT VALID"
      grid_patch: false
      database_patch: true
      datapatch_required: true
