--- # delius_primarydb.yml

database_global_database: TRNDA
database_taf_service: TRNDA_TAF
database_primary_unique: TRNDA
database_primary_sid: TRNDA
delius_users:
  bbuchan_dba:
  rsingh_dba:
  dreid_dba:
  sgandalwar_dba:
  kmoss_dba:
oracle_software:
  version: 19.16
  superset_patch: p34130714_190000_Linux-x86-64.zip
  ojvm_patch: p34086870_190000_Linux-x86-64.zip
  opatch:
    version: 12.2.0.1.32
    filename: p6880880_190000_Linux-x86-64.12.2.0.1.32.zip
database_parameters:
   sga_max_size: 2G
   sga_target: 2G