--- # delius_primarydb.yml

database_global_database: TRNDA
database_taf_service: TRNDA_TAF
database_primary_unique: TRNDA
database_primary_sid: TRNDA
delius_users:
  bbuchan_dba:
  rsingh_dba:
  dreid_dba:
  sgandalwar_dba:
  kmoss_dba: