--- # delius_primarydb.yml

database_global_database: TRNDA
database_taf_service: TRNDA_TAF
database_primary_unique: TRNDA
database_primary_sid: TRNDA
delius_users:
  bbuchan_dba:
  rsingh_dba:
  dreid_dba:
  sgandalwar_dba:
  kmoss_dba:
oracle_software:
      version: 19.12
      superset_patch: p32895426_190000_Linux-x86-64.zip
      ojvm_patch: p32876380_190000_Linux-x86-64.zip
      opatch:
          version: 12.2.0.1.25
          filename: p6880880_190000_Linux-x86-64.zip
audited_interaction_repo: TSTNDA