---

- hosts: localhost
  pre_tasks:

    - name: Checkout our roles repo
      git:
        repo: https://github.com/ministryofjustice/hmpps-ansible-roles.git
        dest: "{{ playbook_dir }}/roles"
        version: "{{ branch|default('master') }}"

    - name: Default to dev (development environments) if target_environment is not set
      set_fact:
        target_environment: "{{ target_environment|default('dev') }}"

    - name: Search for our files that match our target environments
      find:
        paths: "{{ playbook_dir }}"
        recurse: yes
        patterns: "*.credentials.yml, *.credentials.yaml"
      register: all_yaml_files
      when: env_name is not defined

    - name: Search for our files that match our specific environment
      find:
        paths: "{{ playbook_dir }}"
        recurse: yes
        patterns: "{{env_name}}.credentials.yml, {{env_name}}.credentials.yaml"
      register: env_yaml_files
      when: env_name is defined

    - name: Pick the appropriate list of files
      set_fact:
        yaml_files: "{{ env_yaml_files if env_name is defined else all_yaml_files }}"

    - block:
        - name: Filter our results
          set_fact:
            yaml_results: "{{ yaml_files.files | rejectattr('path', 'search', 'common') | map(attribute='path')|list }}"

    - name: Debug our list
      debug:
        msg: "{{ yaml_results }}"

  tasks:
    - name: Run our create credentials role
      include: "{{ playbook_dir }}/local_tasks/run_generation.yml"
      with_items: "{{ yaml_results }}"
      loop_control:
        loop_var: vars_file

  environment:
    ANSIBLE_ROLES_PATH: "{{ playbook_dir }}/roles/roles"

  post_tasks:
    - name: Remove our roles repo
      file:
        path: "{{ playbook_dir }}/roles"
        state: absent
