--- # delius_standbydb1.yml

database_standby_unique: DATNDAS1
database_standby_sid: DATNDAS1
database_parameters:
   sga_max_size: 3280M
   sga_target: 3280M
   pga_aggregate_target: 1640M
   pga_aggregate_limit: 3280M
