--- # misboe_standbydb2.yml

database_standby_unique: DATBOES2
database_standby_sid: DATBOES2
database_parameters:
   sga_max_size: 1G
   sga_target: 1G
required_patches:
    p26749785:
      patch_files:
         - target_version: "19.9"
           filename: p26749785_199000DBRU_Generic.zip
         - target_version: "19.12"
           filename: p26749785_1912000DBRU_Generic.zip
         - target_version: "19.14"
           filename: p26749785_1914000DBRU_Generic.zip
      description: PERF_DIAG NEED TO HAVE MORE CONTROL IN DICTIONARY FOR AUTO_STATS_ADVISOR_TASK
      grid_patch: false
      database_patch: true
      datapatch_required: true