--- # misdsd_standbydb1.yml

database_standby_unique: DATDSDS1
database_standby_sid: DATDSDS1
database_parameters:
   sga_max_size: 1G
   sga_target: 1G
sqlnet_parameters:
   grid:
         SQLNET.INBOUND_CONNECTION_TIMEOUT: 300
   database:
         SQLNET.INBOUND_CONNECTION_TIMEOUT: 300