--- # misdsd_primarydb.yml

database_global_database: DATDSD
database_taf_service: DATDSD_TAF
database_primary_unique: DATDSD
database_primary_sid: DATDSD
database_parameters:
   sga_max_size: 1G
   sga_target: 1G
sqlnet_parameters:
   grid:
         SQLNET.INBOUND_CONNECTION_TIMEOUT: 300
   database:
         SQLNET.INBOUND_CONNECTION_TIMEOUT: 300
delius_users:
  bbuchan_dba:
  rsingh_dba:
  dreid_dba:
  sgandalwar_dba:
  kmoss_dba:
oracle_software:
      version: 19.14
      superset_patch: p33509923_190000_Linux-x86-64.zip
      ojvm_patch: p33561310_190000_Linux-x86-64.zip
      opatch:
          version: 12.2.0.1.29
          filename: p6880880_190000_Linux-x86-64.12.2.0.1.29.zip