--- # mis_primarydb.yml

database_global_database_name: DMTMIS
database_taf_service_name: DMTMIS_TAF
database_primary_unique_name: DMTMIS
database_primary_sid: DMTMIS
required_patches:
    p18841764:
      filename: p18841764_112040_Linux-x86-64.zip
      description: ORA-12592 TNS:BAD PACKET on large datasets
      grid_patch: true
      database_patch: true