--- # delius_primarydb.yml

database_global_database: DNDA
database_taf_service: DNDA_TAF
database_primary_unique: DNDA
database_primary_sid: DNDA
delius_users:
  dbull_ro:
  nmcmahon_ro:
  mrees_ro:
  ahaslehurst_ro:
  bbuchan_dba:
  rsingh_dba:
  dreid_dba:
  sgandalwar_dba:
  kmoss_dba:
oracle_software:
      version: 19.14
      superset_patch: p33509923_190000_Linux-x86-64.zip
      ojvm_patch: p33561310_190000_Linux-x86-64.zip
      opatch:
          version: 12.2.0.1.29
          filename: p6880880_190000_Linux-x86-64.12.2.0.1.29.zip