--- # delius_primarydb.yml

database_global_database: DNDA
database_taf_service: DNDA_TAF
database_primary_unique: DNDA
database_primary_sid: DNDA
delius_users:
  dbull_ro:
  nmcmahon_ro:
  mrees_ro:
  ahaslehurst_ro:
  bbuchan_ro:
     ash_report: true
  bbuchan_dba:
  rsingh_dba:
  dreid_dba:
  sgandalwar_dba:
  kmoss_dba:
oracle_software:
      version: 19.16
      superset_patch: p34130714_190000_Linux-x86-64.zip
      ojvm_patch: p34086870_190000_Linux-x86-64.zip    
      opatch:
          version: 12.2.0.1.32
          filename: p6880880_190000_Linux-x86-64.12.2.0.1.32.zip
audited_interaction_repo: TSTNDA
fsfo_mode: observe
database_locked_statistics:
   - schema_name: DELIUS_APP_SCHEMA
     table_names:
      - DOC_MIGRATION_QUEUE_TAB: ALL