--- # delius-int all.yml
region: eu-west-2
project_name: delius
environment_name: delius-int
simple_environment_name: int
ndelius_version: "4.7.8.6_oracle18c"
catalog: DCAT
data_classification: unclassified-data
database_autotasks:
      sql_tuning_advisor: disabled
      auto_space_advisor: disabled
autotask_windows:
        weekday:
                start_time: "06:20"
                duration_mins: 30
