--- # mis_primarydb.yml

database_global_database: INTMIS
database_taf_service: INTMIS_TAF
database_primary_unique: INTMIS
database_primary_sid: INTMIS
required_patches:
    p32044533:
      patch_files:
         - target_version: "19.9"
           filename: p32044533_199000DBRU_Linux-x86-64.zip
      description: ORA-600 [OPIFCH2:ROWSETSEARLYRET] LOGGED IN DATABASE ALERT LOG
      grid_patch: false
      database_patch: true
      datapatch_required: false
      replaces_patch: "30616738"
