--- # misdsd_primarydb.yml

database_global_database: INTDSD
database_taf_service: INTDSD_TAF
database_primary_unique: INTDSD
database_primary_sid: INTDSD
database_parameters:
   sga_max_size: 1G
   sga_target: 1G
sqlnet_parameters:
   grid:
         SQLNET.INBOUND_CONNECTION_TIMEOUT: 300
   database:
         SQLNET.INBOUND_CONNECTION_TIMEOUT: 300
