plugin: aws_ec2
regions:
  - eu-west-2
keyed_groups:
  # Allow selection by tag eg. hosts: tag_aws_autoscaling_groupName_myasg
  - prefix: tag
    key: tags
hostnames:
  - tag:Name
compose:
  ansible_host: instance_id # Instance ID is used for connecting via SSM Session Manager