plugin: aws_ec2
regions:
  - eu-west-2
keyed_groups:
  # Allow selection by tag eg. hosts: tag_Name_myname
  - prefix: tag
    key: tags
  # Allow selection by ASG name eg. hosts: asg_myasg
  - prefix: asg
    key: tags['aws:autoscaling:groupName']
hostnames:
  - tag:InventoryHost
  - tag:Name
  - instance_id
compose:
  ansible_host: instance_id # Instance ID is used for connecting via SSM Session Manager