--- # mis_standbydb1.yml

database_standby_unique: PREMISS1
database_standby_sid: PREMISS1
database_parameters:
   control_management_pack_access: DIAGNOSTIC
   sga_max_size: 175G
   sga_target: 175G
   pga_aggregate_target: 35G
   pga_aggregate_limit: 70G
required_patches:
    p32044533:
      patch_files:
         - target_version: "19.9"
           filename: p32044533_199000DBRU_Linux-x86-64.zip
      description: ORA-600 [OPIFCH2:ROWSETSEARLYRET] LOGGED IN DATABASE ALERT LOG
      grid_patch: false
      database_patch: true
      datapatch_required: false
      replaces_patch: "30616738"
    p35012866:
      patch_files:
         - target_version: "19.18"
           filename: p35012866_1918000DBRU_Linux-x86-64.zip
      description: "BUG_33527739_APPLY.SQL GOT ORA-13516: AWR OPERATION FAILED: CATPROC NOT VALID"
      grid_patch: false
      database_patch: true
      datapatch_required: true
    p34755459:
      patch_files:
        - target_version: "19.24"
          filename: p34755459_1924000DBRU_Linux-x86-64.zip
        - target_version: "19.25"
          filename: p34755459_1925000DBRU_Linux-x86-64.zip
      description: "ORA-00600 [QERIXGETKEY OPTDESC] WITH FUNCTION BASED INDEX ON SUBSTR"
      grid_patch: false
      database_patch: true
data_guard_parameters:
   ApplyLagThreshold: 1000