--- # misboe_standbydb1.yml

database_standby_unique: PREBOES1
database_standby_sid: PREBOES1
database_parameters:
   sga_max_size: 3G
   sga_target: 3G
   pga_aggregate_target: 2G
   pga_aggregate_limit: 3G