--- # misboe_primarydb.yml

database_global_database: PREBOE
database_taf_service: PREBOE_TAF
database_primary_unique: PREBOE
database_primary_sid: PREBOE
oracle_osbws_chunk_size: 104857600
database_parameters:
   sga_max_size: 3G
   sga_target: 3G
   pga_aggregate_target: 1500M
   pga_aggregate_limit: 3G
rman_retention_policy: RECOVERY WINDOW OF 31 DAYS
required_patches:
    p26749785:
      patch_files:
         - target_version: "19.9"
           filename: p26749785_199000DBRU_Generic.zip
         - target_version: "19.12"
           filename: p26749785_1912000DBRU_Generic.zip
         - target_version: "19.14"
           filename: p26749785_1914000DBRU_Generic.zip
         - target_version: "19.16"
           filename: p26749785_1916000DBRU_Generic.zip
         - target_version: "19.18"
           filename: p26749785_1918000DBRU_Generic.zip
         - target_version: "19.22"
           filename: p26749785_1922000DBRU_Generic.zip
         - target_version: "19.24"
           filename: p26749785_1924000DBRU_Generic.zip
      description: PERF_DIAG NEED TO HAVE MORE CONTROL IN DICTIONARY FOR AUTO_STATS_ADVISOR_TASK
      grid_patch: false
      database_patch: true
      datapatch_required: true
    p35012866:
      patch_files:
         - target_version: "19.18"
           filename: p35012866_1918000DBRU_Linux-x86-64.zip
      description: "BUG_33527739_APPLY.SQL GOT ORA-13516: AWR OPERATION FAILED: CATPROC NOT VALID"
      grid_patch: false
      database_patch: true
      datapatch_required: true
database_autotasks:
      statistics_advisor: disabled
delius_users:
  bbuchan_dba:
  rsingh_dba:
  dreid_dba:
  sgandalwar_dba:
  kmoss_dba:
oracle_software:
      version: '19.22'
      combo_patch: p36031453_190000_Linux-x86-64.zip
      opatch:
          version: 12.2.0.1.41
          filename: p6880880_190000_Linux-x86-64.12.2.0.1.41.zip
rman_level_0_backup_duration_target: "06:00"
fsfo_mode: disabled