--- # misboe_primarydb.yml

database_global_database: PREBOE
database_taf_service: PREBOE_TAF
database_primary_unique: PREBOE
database_primary_sid: PREBOE
oracle_osbws_chunk_size: 104857600
database_parameters:
   sga_max_size: 5G
   sga_target: 5G
   pga_aggregate_target: 256M
rman_retention_policy: RECOVERY WINDOW OF 31 DAYS