--- # misboe_primarydb.yml

database_global_database: PREBOE
database_taf_service: PREBOE_TAF
database_primary_unique: PREBOE
database_primary_sid: PREBOE
oracle_osbws_chunk_size: 104857600
database_parameters:
   sga_max_size: 3G
   sga_target: 3G
   pga_aggregate_target: 1500M
   pga_aggregate_limit: 3G
rman_retention_policy: RECOVERY WINDOW OF 31 DAYS