--- # misdsd_standbydb1.yml

database_standby_unique: PREDSDS1
database_standby_sid: PREDSDS1
database_parameters:
   sga_max_size: 5G
   sga_target: 5G
sqlnet_parameters:
   grid:
         SQLNET.INBOUND_CONNECT_TIMEOUT: 300
   database:
         SQLNET.INBOUND_CONNECT_TIMEOUT: 300
listener_parameters:
   grid:
       INBOUND_CONNECT_TIMEOUT_LISTENER: 300