--- # misdsd_standbydb1.yml

database_standby_unique: PREDSDS1
database_standby_sid: PREDSDS1
database_parameters:
   sga_max_size: 5G
   sga_target: 5G
   db_recovery_file_dest_size: 150G
# SQLNET.INBOUND_CONNECT_TIMEOUT controls timeout for establishing connection to Listener
sqlnet_parameters:
   grid:
         SQLNET.INBOUND_CONNECT_TIMEOUT: 300
   database:
         SQLNET.INBOUND_CONNECT_TIMEOUT: 300
# INBOUND_CONNECT_TIMEOUT_LISTENER controls timeout for establishing connection to Database
listener_parameters:
   grid:
       INBOUND_CONNECT_TIMEOUT_LISTENER: 300
required_patches:
    p35012866:
      patch_files:
         - target_version: "19.18"
           filename: p35012866_1918000DBRU_Linux-x86-64.zip
      description: "BUG_33527739_APPLY.SQL GOT ORA-13516: AWR OPERATION FAILED: CATPROC NOT VALID"
      grid_patch: false
      database_patch: true
      datapatch_required: true