--- # delius_primarydb.yml

database_global_database: POT1NDA
database_taf_service: POT1NDA_TAF
database_primary_unique: POT1NDA
database_primary_sid: POT1NDA
oracle_osbws_chunk_size: 104857600
delius_users:
  bbuchan_dba:
  rsingh_dba:
  dreid_dba:
  sgandalwar_dba:
  kmoss_dba:
oracle_software:
      version: 19.14
      superset_patch: p33509923_190000_Linux-x86-64.zip
      ojvm_patch: p33561310_190000_Linux-x86-64.zip
      opatch:
          version: 12.2.0.1.29
          filename: p6880880_190000_Linux-x86-64.12.2.0.1.29.zip