--- # delius_primarydb.yml

database_global_database: POT1NDA
database_taf_service: POT1NDA_TAF
database_primary_unique: POT1NDA
database_primary_sid: POT1NDA
required_patches:
    p20807155:
      filename: p20807155_112040_Linux-x86-64.zip
      description: ORA-07445 Updating Table with CLOB
      grid_patch: false
      database_patch: true
    p27659043:
      filename: p27659043_11204180417_Linux-x86-64.zip
      description: MES Bundle Patch for April 2018 PSU
      postinstall_sql: postinstall.sql
      grid_patch: false
      database_patch: true
