--- # delius_standbydb1.yml

database_standby_unique: PRDNDAS1
database_standby_sid: PRDNDAS1
database_primary_unique: PRDNDA
database_parameters:
   control_management_pack_access: DIAGNOSTIC+TUNING
   adg_account_info_tracking: LOCAL
   sga_max_size: 50G
   sga_target: 50G
   pga_aggregate_limit: 40G