--- # delius_primarydb.yml

database_global_database: PRDNDA
database_taf_service: PRDNDA_TAF
database_primary_unique: PRDNDA
database_primary_sid: PRDNDA
database_parameters:
   control_management_pack_access: DIAGNOSTIC+TUNING
   adg_account_info_tracking: GLOBAL
rman_level_0_backup_duration_target: "21:00"
rman_uncompressed_backup: Y
rman_retention_policy: RECOVERY WINDOW OF 366 DAYS
cfo_database_directory: "/u01/app/oracle/admin/{{ database_global_database }}/cfo/shared_files/National/cfo"
delius_users:
  nhodgkinson_ro:
  bbuchan_dba:
  rsingh_dba:
  dreid_dba:
  sgandalwar_dba:
  kmoss_dba:
  smauthoor_sro:
  acody_sro:
oracle_software:
  version: 19.14
  superset_patch: p33509923_190000_Linux-x86-64.zip
  ojvm_patch: p33561310_190000_Linux-x86-64.zip
  opatch:
    version: 12.2.0.1.29
    filename: p6880880_190000_Linux-x86-64.12.2.0.1.29.zip
fsfo_mode: observe