--- # delius_primarydb.yml

database_global_database: PRDNDA
database_taf_service: PRDNDA_TAF
database_primary_unique: PRDNDA
database_primary_sid: PRDNDA
database_parameters:
   control_management_pack_access: DIAGNOSTIC+TUNING
   adg_account_info_tracking: LOCAL
rman_level_0_backup_duration_target: "12:00"
rman_uncompressed_backup: Y
rman_retention_policy: RECOVERY WINDOW OF 366 DAYS
cfo_database_directory: "/u01/app/oracle/admin/{{ database_global_database }}/cfo/shared_files/National/cfo"
delius_users:
  nhodgkinson_ro:
  bbuchan_dba:
  rsingh_dba:
  dreid_dba:
  sgandalwar_dba:
  kmoss_dba:
  smauthoor_sro:
  acody_sro:
  worr_sro:
  jmacbeth_ro:
  jdundon_ro:
  mthapa_ro:
  maspin_ro:
  mwetherall_ro:
  mlaskowski_ro:
  pmiller_ro:
  pwilson_ro:
  rmccormack_ro:
  svalmonte_ro:
  yfedkiv_ro:
  abritton_ro:
  smcallister_ro:
  jrobson_ro:
  sbathina_sro:
  dbridgwood_sro:
  achimber_sro:
  mryall_sro:
oracle_software:
      version: 19.18
      combo_patch: p34773504_190000_Linux-x86-64.zip
      opatch:
          version: 12.2.0.1.36
          filename: p6880880_190000_Linux-x86-64.12.2.0.1.36.zip
database_locked_statistics:
   - schema_name: DELIUS_APP_SCHEMA
     table_names:
      - DOC_MIGRATION_QUEUE_TAB: ALL
awr_retention_days: 40
required_patches:
    p35012866:
      patch_files:
         - target_version: "19.18"
           filename: p35012866_1918000DBRU_Linux-x86-64.zip
      description: "BUG_33527739_APPLY.SQL GOT ORA-13516: AWR OPERATION FAILED: CATPROC NOT VALID"
      grid_patch: false
      database_patch: true
      datapatch_required: true