--- # mis_primarydb.yml

database_global_database: PRDMIS
database_taf_service: PRDMIS_TAF
database_primary_unique: PRDMIS
database_primary_sid: PRDMIS
database_parameters:
   control_management_pack_access: DIAGNOSTIC
rman_retention_policy: RECOVERY WINDOW OF 366 DAYS
required_patches:
    p18841764:
      filename: p18841764_112040_Linux-x86-64.zip
      description: ORA-12592 TNS:BAD PACKET on large datasets
      grid_patch: true
      database_patch: true