--- # mis_primarydb.yml

database_global_database: PRDMIS
database_taf_service: PRDMIS_TAF
database_primary_unique: PRDMIS
database_primary_sid: PRDMIS
database_parameters:
   control_management_pack_access: DIAGNOSTIC
   sga_max_size: 175G
   sga_target: 175G
   pga_aggregate_target: 35G
   pga_aggregate_limit: 70G
rman_retention_policy: RECOVERY WINDOW OF 366 DAYS
rman_level_0_backup_duration_target: "15:00"
rman_uncompressed_backup: Y
