--- # mis_standbydb1.yml

database_standby_unique: PRDMISS1
database_standby_sid: PRDMISS1
database_parameters:
   control_management_pack_access: DIAGNOSTIC
   sga_max_size: 175G
   sga_target: 175G
   pga_aggregate_target: 35G
   pga_aggregate_limit: 70G
