--- # misboe_standbydb1.yml

database_standby_unique: PRDBOES1
database_standby_sid: PRDBOES1
database_parameters:
   control_management_pack_access: DIAGNOSTIC
   sga_max_size: 3G
   sga_target: 3G
   pga_aggregate_target: 1500M
   pga_aggregate_limit: 3500M
required_patches:
    p26749785:
      patch_files:
         - target_version: "19.9"
           filename: p26749785_199000DBRU_Generic.zip
      description: PERF_DIAG NEED TO HAVE MORE CONTROL IN DICTIONARY FOR AUTO_STATS_ADVISOR_TASK
      grid_patch: false
      database_patch: true
      datapatch_required: true   