--- # misboe_primarydb.yml

database_global_database: PRDBOE
database_taf_service: PRDBOE_TAF
database_primary_unique: PRDBOE
database_primary_sid: PRDBOE
database_parameters:
   control_management_pack_access: DIAGNOSTIC
   sga_max_size: 3G
   sga_target: 3G
   pga_target: 2G
rman_retention_policy: RECOVERY WINDOW OF 366 DAYS
