--- # misboe_standbydb2.yml

database_standby_unique: PRDBOES2
database_standby_sid: PRDBOES2
database_parameters:
   control_management_pack_access: DIAGNOSTIC
   sga_max_size: 3G
   sga_target: 3G
   pga_aggregate_target: 1500M
   pga_aggregate_limit: 3500M