--- # misboe_standbydb1.yml

database_standby_unique: PRDBOES1
database_standby_sid: PRDBOES1
database_parameters:
   control_management_pack_access: DIAGNOSTIC
   sga_max_size: 3G
   sga_target: 3G
   pga_target: 2G