--- # delius_standbydb1.yml

database_standby_unique: DMDNDAS1
database_standby_sid: DMDNDAS1
database_parameters:
   db_recovery_file_dest_size: 450G
required_patches:
  p36252161:
    patch_files:
      - target_version: "19.22"
        filename: p36252161_1922000OCWRU_Linux-x86-64.zip
    description: UNSUPPORTED CONFIGURATION DETECTED FOR REAL-TIME SCHEDULING REQUIREMENTS.
    grid_patch: true
    database_patch: false
    datapatch_required: false
    install_with_opatchauto: true