--- # mis_standbydb1.yml

database_standby_unique: DMDMISS1
database_standby_sid: DMDMISS1
required_patches:
    p18841764:
      filename: p18841764_112040_Linux-x86-64.zip
      description: ORA-12592 TNS:BAD PACKET on large datasets
      grid_patch: true
      database_patch: true