--- # misboe_primarydb.yml

database_global_database: DMDBOE
database_taf_service: DMDBOE_TAF
database_primary_unique: DMDBOE
database_primary_sid: DMDBOE
database_parameters:
   sga_max_size: 1G
   sga_target: 1G
required_patches:
    p26749785:
      filename: p26749785_199000DBRU_Generic.zip
      description: PERF_DIAG NEED TO HAVE MORE CONTROL IN DICTIONARY FOR AUTO_STATS_ADVISOR_TASK
      grid_patch: false
      database_patch: true
      datapatch_required: true
      target_version: "19.9"
database_autotasks:
      statistics_advisor: disabled