--- # misboe_primarydb.yml

database_global_database: DMDBOE
database_taf_service: DMDBOE_TAF
database_primary_unique: DMDBOE
database_primary_sid: DMDBOE
database_parameters:
   sga_max_size: 1G
   sga_target: 1G
required_patches:
    p26749785:
      patch_files:
          - target_version: "19.9"
            filename: p26749785_199000DBRU_Generic.zip
          - target_version: "19.12"
            filename: p26749785_1912000DBRU_Generic.zip
          - target_version: "19.14"
            filename: p26749785_1914000DBRU_Generic.zip
          - target_version: "19.16"
            filename: p26749785_1916000DBRU_Generic.zip
      description: PERF_DIAG NEED TO HAVE MORE CONTROL IN DICTIONARY FOR AUTO_STATS_ADVISOR_TASK
      grid_patch: false
      database_patch: true
      datapatch_required: true
database_autotasks:
      statistics_advisor: disabled
delius_users:
  bbuchan_dba:
  rsingh_dba:
  dreid_dba:
  sgandalwar_dba:
  kmoss_dba:
oracle_software:
  version: 19.16
  superset_patch: p34130714_190000_Linux-x86-64.zip
  ojvm_patch: p34086870_190000_Linux-x86-64.zip
  opatch:
    version: 12.2.0.1.32
    filename: p6880880_190000_Linux-x86-64.12.2.0.1.32.zip
