--- # misboe_primarydb.yml

database_global_database: DMDBOE
database_taf_service: DMDBOE_TAF
database_primary_unique: DMDBOE
database_primary_sid: DMDBOE
database_parameters:
   sga_max_size: 1G
   sga_target: 1G
required_patches:
    p26749785:
      patch_files:
          - target_version: "19.9"
            filename: p26749785_199000DBRU_Generic.zip
          - target_version: "19.12"
            filename: p26749785_1912000DBRU_Generic.zip
      description: PERF_DIAG NEED TO HAVE MORE CONTROL IN DICTIONARY FOR AUTO_STATS_ADVISOR_TASK
      grid_patch: false
      database_patch: true
      datapatch_required: true
database_autotasks:
      statistics_advisor: disabled
delius_users:
  bbuchan_dba:
  rsingh_dba:
  dreid_dba:
  sgandalwar_dba:
  kmoss_dba: