--- # misboe_primarydb.yml

database_global_database: DMDBOE
database_taf_service: DMDBOE_TAF
database_primary_unique: DMDBOE
database_primary_sid: DMDBOE
database_parameters:
   sga_max_size: 3G
   sga_target: 3G
   db_recovery_file_dest_size: 90G
required_patches:
    p26749785:
      patch_files:
          - target_version: "19.9"
            filename: p26749785_199000DBRU_Generic.zip
          - target_version: "19.12"
            filename: p26749785_1912000DBRU_Generic.zip
          - target_version: "19.14"
            filename: p26749785_1914000DBRU_Generic.zip
          - target_version: "19.16"
            filename: p26749785_1916000DBRU_Generic.zip
          - target_version: "19.18"
            filename: p26749785_1918000DBRU_Generic.zip
          - target_version: "19.20"
            filename: p26749785_1920000DBRU_Generic.zip
          - target_version: "19.22"
            filename: p26749785_1922000DBRU_Generic.zip
          - target_version: "19.24"
            filename: p26749785_1924000DBRU_Generic.zip
      description: PERF_DIAG NEED TO HAVE MORE CONTROL IN DICTIONARY FOR AUTO_STATS_ADVISOR_TASK
      grid_patch: false
      database_patch: true
      datapatch_required: true
database_autotasks:
      statistics_advisor: disabled
delius_users:
  bbuchan_dba:
  rsingh_dba:
  dreid_dba:
  sgandalwar_dba:
  kmoss_dba:
oracle_software:
      version: '19.22'
      combo_patch: p36031453_190000_Linux-x86-64.zip
      opatch:
          version: 12.2.0.1.41
          filename: p6880880_190000_Linux-x86-64.12.2.0.1.41.zip
